services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v2.4.0
    container_name: homepage
    restart: unless-stopped

    environment:
      HOMEPAGE_ALLOWED_HOSTS: homepage.home.arpa
      NODE_EXTRA_CA_CERTS: /etc/ssl/certs/caddy-root.crt
      HOMEPAGE_VAR_ADGUARD_USER: ${HOMEPAGE_VAR_ADGUARD_USER}
      HOMEPAGE_VAR_ADGUARD_PASS: ${HOMEPAGE_VAR_ADGUARD_PASS}
      HOMEPAGE_VAR_WUD_USER: ${HOMEPAGE_VAR_WUD_USER}
      HOMEPAGE_VAR_WUD_PASS: ${HOMEPAGE_VAR_WUD_PASS}
      HOMEPAGE_VAR_PAPERLESS_TOKEN: ${HOMEPAGE_VAR_PAPERLESS_TOKEN}

    volumes:
      - /srv/appdata/homepage/config:/app/config
      - /srv/appdata/homepage/certs/caddy-root.crt:/etc/ssl/certs/caddy-root.crt:ro

    networks:
      - proxy

networks:
  proxy:
    external: true
