services:
  wud:
    image: getwud/wud:8.3.1
    container_name: wud
    restart: unless-stopped

    ports:
      - "${WUD_BIND_ADDRESS}:${WUD_PORT}:3000"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - "${WUD_DATA_PATH}:/store"

    environment:
      TZ: "${TZ}"
      WUD_WATCHER_LOCAL_WATCHBYDEFAULT: "true"
      WUD_WATCHER_LOCAL_CRON: "0 * * * *"
