services:
  caddy:
    image: caddy:2.11.4-alpine
    container_name: caddy
    restart: unless-stopped

    ports:
      - "${CADDY_BIND_ADDRESS}:80:80"
      - "${CADDY_BIND_ADDRESS}:443:443"
      - "${CADDY_BIND_ADDRESS}:443:443/udp"

    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - "${CADDY_DATA_PATH}/data:/data"
      - "${CADDY_DATA_PATH}/config:/config"

    networks:
      - proxy

networks:
  proxy:
    external: true
